# $NetBSD: Makefile.common,v 1.6 2018/04/12 08:25:24 he Exp $
# used by sysutils/zabbix/Makefile
# used by sysutils/zabbix-frontend/Makefile

VER=		4.0.4
DISTNAME=	zabbix-${VER}
PKGNAME=        zabbix-proxy-${VER}
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=zabbix/}

MAINTAINER?=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://www.zabbix.com/
LICENSE=	gnu-gpl-v2

DISTINFO_FILE=	${.CURDIR}/../../erigones/zabbix-proxy/distinfo
PATCHDIR=	${.CURDIR}/../../erigones/zabbix-proxy/patches
