# $NetBSD: Makefile.common,v 1.6 2018/04/12 08:25:24 he Exp $
# used by sysutils/zabbix/Makefile
# used by sysutils/zabbix-frontend/Makefile

VER=		4.0.6
DISTNAME=	zabbix-${VER}
PKGNAME=	zabbix-agent-${VER}
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=zabbix/}

MAINTAINER?=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://www.zabbix.com/
LICENSE=	gnu-gpl-v2

DISTINFO_FILE=	${.CURDIR}/../../erigones/zabbix-agent/distinfo
PATCHDIR=	${.CURDIR}/../../erigones/zabbix-agent/patches
